<template>
  <v-container class="mt-12">
    <v-row class="flex flex-row items-center mb-8">
      <h3 class="text-navy leading-tight">Seven Habits of a Highly Impactful Chief Data Officer (CDO)</h3>
      <p>The Chief Data Officer (CDO) is the most senior executive responsible for advocating and promoting data as a strategic enterprise asset. The CDO role is rapidly evolving, and their success is critical to driving an organization's growth and innovation charter. CDOs must embrace their role as change agents, and shift from a defensive mindset of data governance & technical expertise to an offensive data strategy by identifying and driving a portfolio of business use cases.</p><br />
      <p>According to a recent Gartner report, 50% of CDOs will fail due to a combination of internal and external factors. Because many external factors are beyond their direct control, the CDO must be aware of key internal impediments to success. The following is a guide to identifying the behavioral habits that we believe CDOs should have.</p>
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit One – Ownership</h5>
      <p>Takes responsibility for acting as a catalyst across the organization to identify the highest value portfolio of use cases and how these use cases can be delivered as curated data products for consumption by AI, BI, and analytical teams.</p><br />
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit Two – Collaborator</h5>
      <p>Build relationships and communication that facilitate constructive collaboration that prioritizes business outcomes to discover the data landscape and has an active inventory of enterprise data sets.</p><br />
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit Three – Storyteller</h5>
      <p>The ability to craft and deliver a narrative to multiple stakeholders to build empathy and support for how data can be profiled to drive business outcomes.</p><br />
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit Four – Bias for Action</h5>
      <p>The pace is set on multiple fronts, with technical platforms leveraging pre-assembled cloud services, driving multiple use cases, and engaging across multiple business lines. Starting small but scaling quickly to demonstrate value, and failing quickly, with no blame and learning.</p><br />
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit Five – Bridge Builder</h5>
      <p>Bridges data silos within the organization and with external providers to proliferate an active metadata repository but also ensure interoperability of integration between incumbent and cloud tool providers.</p><br />
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit Six – Advocate</h5>
      <p>To realize the value of data, CDOs must democratize and build an insights-driven organization through Data Products and make these available through Data Marketplace, allowing the monetization of data assets across the organization.</p><br />
    </v-row>
    <v-row class="my-4 flex flex-col">
      <h5 class="text-modak-blue">Habit Seven – Monetizes Data Products</h5>
      <p>Data not only fuels analytics but also unlocks insights generated by AI and machine learning algorithms to help answer the questions of tomorrow. As these algorithms improve the accuracy and types of insights generated with more data, the CDO needs to build “data flywheels” that continuously fuel AI models.</p><br />
    </v-row>
    <v-row class="my-4">
      <h5 class="text-navy">About Modak</h5>
      <p>Modak is a solutions company that enables enterprises to manage and utilize their data landscape effectively. We
        provide cloud-agnostic software and services to accelerate data migration initiatives. We use machine learning
        (ML) techniques to transform how structured and unstructured data is prepared, consumed, and shared.</p>
      <br />
      <p>Modak’s portfolio of Data Engineering Studio provides best-in-class delivery services, managed data operations,
        data mesh, data fabric, augmented data preparation, data quality, and governed data lake solutions.</p><br />
      <p>To learn more, please download: <a href="https://modak.com/modak-nabu-solution/"
          class="no-underline text-modak-blue">https://modak.com/modak-nabu-solution/</a></p>
    </v-row>
    <v-row class="my-4">
      <h5 class="text-navy">Modak Nabu™</h5>
      <p>Modak Nabu™ enables enterprises to automate data ingestion, curation, and consumption processes at a petabyte-scale. Modak Nabu™ empowers tomorrow's smart enterprises to create repeatable and scalable business data domain products that improve the efficiency and effectiveness of business users, data scientists, and BI analysts in finding the appropriate data, at the right time, and in the right context.</p>
    </v-row>
    <v-row>
      <h5 class="text-navy w-full">Author:</h5><br />
      <v-col class="text-left">
        <v-avatar size="90">
          <v-img
            src="https://1lzctcc4hd2zm.cdn.shift8web.com/wp-content/uploads/2021/09/aarti-1-160x160.png.webp"></v-img>
        </v-avatar>
        <span class="font-oswald block font-medium text-xl text-modak-blue mt-4">Aarti Joshi</span>
        <span>Chief Executive Officer, Modak</span>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  setup() {
    return {}
  }
}
</script>

<style lang="scss" scoped>.v-container {
  max-width: 1200px;
}</style>